-- CreateTable
CREATE TABLE "session" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sessionName" STRING NOT NULL,
    "sessionTime" STRING NOT NULL,
    "sessionDuration" INT4 NOT NULL,
    "maxUsers" INT4 NOT NULL,

    CONSTRAINT "session_pkey" PRIMARY KEY ("id")
);
